### ISSUE TITLE
script will fail if no links are in the given folder

### ISSUE THREAD

**Issue by carfesh** [ltsdw/gofile-downloader#10]
Thanks for this great script. I have one issue with it:
When no files are in the given folder, but instead in subfolders (I believe the script does not recurse yet?), it will just throw an error.
Is the possibility to recurse through subfolders something you'd be willing to look into?

**Comment by ltsdw** [comment]
Thank you for your report.

> Is the possibility to recurse through subfolders something you'd be willing to look into?

Sure, can I have a link where this case is reproducible?

**Comment by carfesh** [comment]
I believe this should do as a test: https://gofile.io/d/0ce5a6fb-28df-4259-93b5-4434ae319d4b

**Comment by ltsdw** [comment]
It isn't public, can you provide another one?

**Comment by carfesh** [comment]
Does this one work? https://gofile.io/d/UsAwKk
I can't seem to find the one I was trying earlier, but I've created one myself.

**Comment by ltsdw** [comment]
Ok, can you please test out the latest commit: [allow to recursively download files](https://github.com/ltsdw/gofile-downloader/commit/6136a3a016115f911acfcfc0eea1e0b0b40e80d3)

I may have introduced some regressions, didn't do extensive testing, if so please report them.

Thank you.

**Comment by carfesh** [comment]
It's working fine for me - awesome! Thank you for solving this so quickly!
