### ISSUE TITLE
Does not download, gofile API changed?

### ISSUE THREAD

**Issue by femscat** [ltsdw/gofile-downloader#13]
Worked fine until a couple of weeks, looks like gofile changed something. This is the output with any link:

Failed to get a link as response from the https://api.gofile.io/getContent?contentId=******&token=okGK6dePeyNlxTuguN2EaBepwV1Ti8EG&websiteToken=12345&cache=true

**Comment by ltsdw** [comment]
Thank you for you're report, I'll have a look at it soon.

**Comment by ltsdw** [comment]
@femscat yes, actually gofile now requires a premium account to use getContent, getAccountDetails, etc: [API](https://gofile.io/api).

If you have one, you just need to provide your premium account token, as: `./gofile-downloader your-token thecontenturl`.
