### ISSUE TITLE
Where do i get the your-premium-account-token-here token?

### ISSUE THREAD

**Issue by PeterMeir** [ltsdw/gofile-downloader#14]
Hello. First of all thank you very much for sharing this with everyone.
What do i type for "your-premium-account-token-here". Like where can i get or see that?

**Comment by ltsdw** [comment]
Hello there!

If you already have a premium account you have to click on the profile picture at top left of the gofile site, go to account settings and at the bottom of the window you'll see your "token api" (it's that one that you want).

If you still not found it you can contact their support channel through email 😄 .

**Comment by ninjaduck4112636** [comment]
Hi @ltsdw is there a way to use your project to download files with out premium token because before we where able to sownload the files without the premium token 

```
_id: str = uploads.download_page.split("/")[-1]

create_account_response: Dict = get("https://api.gofile.io/createAccount").json()

api_token = create_account_response["data"]["token"]

account_response: Dict = get("https://api.gofile.io/getAccountDetails?token=" + api_token).json()

_url: str = f"https://api.gofile.io/getContent?contentId={_id}&token={api_token}&websiteToken=12345&cache=true"```

Now i am getting this as the response 

```
{"status":"error-notPremium","data":{}}
```

**Comment by ninjaduck4112636** [comment]
![Screenshot from 2023-06-24 16-08-27](https://github.com/ltsdw/gofile-downloader/assets/71088270/9c8c8979-590a-4d4a-bc15-c9abe53bcbd9)

**Comment by ltsdw** [comment]
Sadly no, gofile started requiring premium account to use its API recently.

I would have to write a scraper to make it work without using the gofile's API (which would be a bit slower than using the gofile's API to fetch data). But I'm a bit busy.

**Comment by ninjaduck4112636** [comment]
If you could tell me the step-by-step process in which we could scrape the data to make this work, without the official API i could help write the partial code. As i am also busy this week i will try writing as much code as i can. Thanks 😊

**Comment by ltsdw** [comment]
It's easy, any web scraping tutorial on the internet will get you through it. 😃 

My jpg-church downloader is a web scraping script, you can read that one to have an idea.

**Comment by ninjaduck4112636** [comment]
Sure, Thanks 😊

**Comment by ltsdw** [comment]
@ninjaduck4112636 @PeterMeir as of now this wrapper doesn't require premium account anymore. Thanks to @ChaudharySaurav

Closing as 87901258a5008d88903cb1b8240f91725f950552.
