### ISSUE TITLE
Environment Variable Help

### ISSUE THREAD

**Issue by RandomGuy5598** [ltsdw/gofile-downloader#16]
I'm not sure if I'm missing something here...

What value do I set when making a GF_DOWNLOADDIR variable? Or is there some other way I'm supposed to be going about this?

Not really an important issue. I can just move the downloads to wherever I want after completion. I was just curious how I could go about getting this working, if possible. Quality of life type of thing.

Either way, thank you! :)
Cheers!

**Comment by ltsdw** [comment]
Hello there!

You should put the directory path you want to use. So for example, if I have a path like `/home/.local/Desktop/Downloads` and I want to use that directory path to put the files I download in it. It would look like this:

```
GF_DOWNLOADDIR="/home/.local/Desktop/Downloads" python gofile-downloader.py https://gofile.io/d/contentid
```

Also it's worth to noting that the directory must exist already, as the script won't create it and will fallback to the current directory in case the specified directory doesn't exist, also the directory must have permissions of read and write, failing to access the directory it will fallback to the current directory.

**Comment by ltsdw** [comment]
That's cool, could you please show me how you're doing it?

**Comment by ltsdw** [comment]
Closing, if you still have problems please open this issue again.
