### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by Sonic3R** [ltsdw/gofile-downloader#18]
Hi,

I run `pip install requirements.txt` but I'm giving:

> ERROR: Could not find a version that satisfies the requirement requirements.txt
ERROR: No matching distribution found for requirements.txt

**Comment by ltsdw** [comment]
Could you please try `pip -r install requirements.txt`, without the -r flag pip thinks it should install a module named `requirements.txt`, which doesn't exists.

**Comment by Sonic3R** [comment]
Yes, my bad.
