### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by Sonic3R** [ltsdw/gofile-downloader#19]
Hi,

I run script in linux with python `Python 3.9.2`:

`python3 gofile-downloader.py https://gofile.io/d/aBcDeF`

or

`./gofile-downloader.py https://gofile.io/d/aBcDeF`

and I get 

> Traceback (most recent call last):
  File "/home/myuser/tools/gofile-downloader/gofile-downloader.py", line 48, in <module>
    class Main:
  File "/home/myuser/tools/gofile-downloader/gofile-downloader.py", line 49, in Main
    def __init__(self, url: str, password: str | None = None, max_workers: int = 5) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by ltsdw** [comment]
Hello, could you please check this https://github.com/ltsdw/gofile-downloader/issues/4#issuecomment-1223643143?

Basically you need at least python 3.10.

**Comment by ltsdw** [comment]
It means that python can't find the modules pip installed, can you check which pip version you have? Maybe it's using python2 insteand of python3.

Try running `pip3 install -r requirements.txt` and see if that changes something.

**Comment by Sonic3R** [comment]
Oh, my second fault, I had to use pip3 for installing

it works now
