### ISSUE TITLE
It gives an error

### ISSUE THREAD

**Issue by AAK581** [ltsdw/gofile-downloader#20]
Failed to get a link as response from the https://api.gofile.io/getContent?contentId=nWXU7Q&token=8H9qKVYjhWupDJJnrZKjdh5jpSRurLcm&wt=4fd6sg89d7s6&cache=true

**Comment by AAK581** [comment]
https://gofile.io/d/nWXU7Q

**Comment by ltsdw** [comment]
It seems quite right, as the content on the link you provided doesn't exist.

**Comment by AAK581** [comment]
Doesn't exist? Weird, Multiup shows it exists, but yeah it sometimes screws that up as well XD

**Comment by ltsdw** [comment]
Haha, normal thing then.

Yeah, the link you provided says that the file does not exist, probably it went some time without downloads and gofile deleted it (it expired as to say).
