### ISSUE TITLE
Account creation failed

### ISSUE THREAD

**Issue by Nemes94** [ltsdw/gofile-downloader#23]
Sometimes the script gives an error.

> Starting, please wait...
> Account creation failed!
> Command failed with return code 4294967295

How can i solve the problem?

**Comment by ltsdw** [comment]
It's working normally here, if it works sometimes for you, and sometimes it doesn't, it can be some things, it can be the Gofile's API that's busy or it can be the API refusing to respond to your ISP requests, either way there's nothing my script can do in those cases, sadly.
