### ISSUE TITLE
Download directly file to working directory without creating subfolders

### ISSUE THREAD

**Issue by Sonic3R** [ltsdw/gofile-downloader#29]
Hello,

What line(s) should change in order to download file directly without nested folders ?

I mean if I use 

```
./gofile-downloader.py https://gofile.io/d/AbCdEf
```
and it has 1 file inside, I want to put directly in current working directory.

Now, the script creates the following folder structure: `AbCdEf/AbCdEf/this_is_file.mp4` which I see is duplicated.

If there is alot of files, then create one single structure `AbCdEf` not doubled.

**Comment by ltsdw** [comment]
Hello there o/

Should be fixed by https://github.com/ltsdw/gofile-downloader/commit/c98ecceac1edcc75101be7ae99850c03d507efa4.

Closing.

**Comment by Sonic3R** [comment]
There is error

‘’’
"/tools/gofile/gofile-downloader.py", line 165
    "Referer": f"{url}{("/" if not url.endswith("/") else "")}",
                         ^
SyntaxError: f-string: unmatched '('
‘’’

**Comment by ltsdw** [comment]
Weird, because I didn't touched this part of the function. Was it working before?

Can you try this change:

```patch
-"Referer": f"{url}{("/" if not url.endswith("/") else "")}",
+"Referer": f"{url}{('/' if not url.endswith('/') else '')}",
``` 

And see if it works.

**Comment by Sonic3R** [comment]
Yes that line and other two lines from 239 as well, now is working fine

thanks

**Comment by ltsdw** [comment]
Thank you for the feedback, do you mean that the line 239 have this happening too?
