### ISSUE TITLE
Add shebang

### ISSUE THREAD

**Issue by kattjevfel** [ltsdw/gofile-downloader#3]
Kind of a nitpick, but could you please add a shebang to the script, so that users can run the script directly without prefixing it with `python`?

`#!/usr/bin/env python3` should be fine

**Comment by ltsdw** [comment]
sure thing [Add shebang line](https://github.com/ltsdw/gofile-downloader/commit/41119d8ec3e4ab031300ff7ed5fac528e9421f29)

thank you 😄 

closing.
