### ISSUE TITLE
Download stops at 1.6% consistently

### ISSUE THREAD

**Issue by 00BBL** [ltsdw/gofile-downloader#31]
At least with the file I'm downloading, consistent stoppage at 1.6%

**Comment by ltsdw** [comment]
Usually when this happens it's a problem with gofile's API and trying again after some time makes it work.

But if it still happening I can have a look later, just leave a link to the pr

**Comment by ltsdw** [comment]
Closing, if the issue persist don't hesitate to reopen :)
