### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by heshanthenura** [ltsdw/gofile-downloader#32]
ubuntu@ubuntu:~/name/gofile-downloader$ python3 gofile-downloader.py https://gofile.io/d/LltlL3
Traceback (most recent call last):
  File "gofile-downloader.py", line 51, in <module>
    class Main:
  File "gofile-downloader.py", line 146, in Main
    def _download_content(self, file_info: dict[str, str], chunk_size: int = 16384) -> None:
TypeError: 'type' object is not subscriptable
ubuntu@ubuntu:~/codgame/gofile-downloader$

**Comment by ltsdw** [comment]
Hello there, your python version is 3.9 or earlier, you need python 3.10 or later.
See #9
