### ISSUE TITLE
 'type' and 'NoneType'

### ISSUE THREAD

**Issue by Falcon87262** [ltsdw/gofile-downloader#4]
Hi 
i keep getting this error can you tell me how to resolve it

` python gofile-downloader.py https://gofile.io/d/GLankA
Traceback (most recent call last):
  File "gofile-downloader.py", line 34, in <module>
    class Main:
  File "gofile-downloader.py", line 35, in Main
    def __init__(self, url: str, password: str | None = None, max_workers: int = 5) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by ltsdw** [comment]
Hi, can you please run it with python3, like this:

```
python3 gofile-downloader.py https://gofile.io/d/GLankA
```
and tell me if it works.

**Comment by ltsdw** [comment]
Also check if your python version is at least 3.10, as:

[PEP 604 – Allow writing union types as X | Y](https://peps.python.org/pep-0604/)

**Comment by ltsdw** [comment]
If you still having problema feel free to re open it.
Closing.
