### ISSUE TITLE
Error after downloading 42 of 210

### ISSUE THREAD

**Issue by undecidedm8** [ltsdw/gofile-downloader#6]
Why would this be happening?

`Traceback (most recent call last):
  File "D:\potat0\Downloads\gofile-downloader-main\gofile-downloader.py", line 218, in <module>
    Main(url=url, password=password)`

 `File "D:\potat0\Downloads\gofile-downloader-main\gofile-downloader.py", line 54, in __init__
    self._threadedDownloads()`

  `File "D:\potat0\Downloads\gofile-downloader-main\gofile-downloader.py", line 65, in _threadedDownloads
    for link in self._getLinks(self._url, self._password):`

  `File "D:\potat0\Downloads\gofile-downloader-main\gofile-downloader.py", line 193, in _getLinks
    yield content["link"]
KeyError: 'link'`

**Comment by ltsdw** [comment]
Basically it's telling that for whatever reason, it couldn't get the download link for the that item in specifics.

I was planning getting better error messages and tunable number of parallel downloads, but my notebook died.

you can try opening the gofile-downloader.py and changing the max_workers from this line

```
def __init__(self, url: str, password: str | None = None, max_workers: int = 5) -> None:
```

from 5 to 1, or maybe if doesn't work try changing from 5 to a greater number.

**Comment by undecidedm8** [comment]
Changing the workers from 5 to 1 fixed it. Thank you so much. I would have never thought to change this
