### ISSUE TITLE
Go-File uploader stuck after a few files

### ISSUE THREAD

**Issue by iTimELeZz** [ltsdw/gofile-downloader#7]
Hey, 
Ive got the issue that on some container, the downloader start to download a few files and then just stuck at one file 

OS: macOS Monterey
Python Version: Python 3.10.5

**Comment by ltsdw** [comment]
Strange never had one of those, can you please try the suggestion over #6 ?

**Comment by ltsdw** [comment]
also may be just some momentary instability with gofile's api

**Comment by iTimELeZz** [comment]
Yeah you was right, tried again, and now worked, so must be an API issue. Thanks
