### ISSUE TITLE
error: line 14 NEW_LINE SyntaxError

### ISSUE THREAD

**Issue by NeoHBz** [ltsdw/gofile-downloader#8]
<img width="652" alt="Screenshot 2022-09-22 at 3 52 44 PM" src="https://user-images.githubusercontent.com/56602090/191723733-5a82cacd-2408-4ab9-b827-b16d08e087e1.png">

**Comment by ltsdw** [comment]
[Your python version needs to be at least 3.10](https://github.com/ltsdw/gofile-downloader/issues/4#issuecomment-1223643143)

**Comment by NeoHBz** [comment]
fixed after upgrading python to version 3.10 👍
closing
